# Generated by Django 2.2.19 on 2022-01-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220124_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(
                max_length=60, 
                primary_key=True, 
                serialize=False),
        ),
    ]
